---
openapi: 3.0.0
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: List all users
      tags:
      - Users
      responses:
        '200':
          description: Successful
        '401':
          description: Authentication Failed
    post:
      summary: Create User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
        '401':
          description: Authentication Failed
        '422':
          description: Invalid User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    nickname:
                      type: string
                    password:
                      type: string
        required: true
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: id
      schema:
        type: string
    get:
      summary: Show User
      tags:
      - Users
      responses:
        '200':
          description: Successful
        '401':
          description: Authentication Failed
        '404':
          description: User not found
    delete:
      summary: Delete User
      tags:
      - Users
      responses:
        '200':
          description: Successful
        '401':
          description: Authentication Failed
        '403':
          description: Only the owner of the user can delete it.
    patch:
      summary: Update User
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Successful
        '401':
          description: Authentication Failed
        '422':
          description: Invalid User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    nickname:
                      type: string
                    password:
                      type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: ''
security:
- bearerAuth: []
